export const JoystickKeyMap = {
    '96': 'A',
    '97': 'B',
    '98': 'C',
    '99': 'X',
    '100': 'Y',
    '101': 'Z',
    '102': 'L1',
    '103': 'R1',
    '104': 'L2',
    '105': 'R2',
    '106': 'Left thumb',
    '107': 'Right thumb',
    '108': 'Start',
    '109': 'Select',
    '110': 'Mode',
    'leftX' :'Left X',
    'leftY' :'Left Y',
    'rightX' :'Right X',
    'rightY' :'Right Y',
    'hatX' :'Hat X',
    'hatY' :'Hat Y',
    'leftTrigger' :'Left Trigger',
    'rightTrigger' :'Right Trigger',
}